name: CI/CD Pipeline for Blockchain DApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          npm install -g truffle
          npm install -g ganache-cli

      - name: Start Ganache CLI
        run: ganache-cli --defaultBalanceEther 1000 --deterministic > /dev/null 2>&1 &
        shell: bash

      - name: Compile Contracts
        run: truffle compile

      - name: Run Unit Tests
        run: truffle test

      - name: Capture Ganache CLI Output for Debugging
        run: cat ganache-output.txt
