name: CI/CD Pipeline for D'App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Compile Contracts
        run: |
          npx hardhat compile

      - name: Run Unit Tests
        run: |
          cd contracts
          npx hardhat test --network hardhat

  #     - name: Deploy to Goerli Testnet
  #       if: github.ref == 'refs/heads/main'
  #       env:
  #         PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  #         INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
  #       run: |
  #         npx hardhat run scripts/deploy.js --network goerli

  #     - name: Verify Contract on Etherscan
  #       if: github.ref == 'refs/heads/main'
  #       env:
  #         ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  #       run: |
  #         npx hardhat verify --network goerli <DEPLOYED_CONTRACT_ADDRESS> <CONSTRUCTOR_ARGUMENTS>

  #     - name: Notify on Success
  #       if: github.ref == 'refs/heads/main'
  #       run: |
  #         echo "Deployment to Goerli Testnet successful!"

  # monitoring:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Check out the repository
  #       uses: actions/checkout@v2

  #     - name: Continuous Monitoring
  #       run: |
  #         echo "Monitoring deployed contract activity on Goerli Testnet..."

  #     - name: Set Up Alerts
  #       run: |
  #         echo "Setting up alerts for contract events..."
