name: Blockchain App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Dcker run
      run: docker run --name bcapp -p 3000:3000 -d pavanvarikolu/blockchainapp:latest
