name: CI/CD Pipeline for Blockchain DApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      ganache:
        image: trufflesuite/ganache-cli
        options: "--host 0.0.0.0 --port 7545 --defaultBalanceEther 1000"
        ports:
          - 7545:7545

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          npm install -g truffle

      - name: Compile Contracts
        run: truffle compile

      - name: Run Unit Tests
        run: truffle test

      - name: List directory contents (Debugging)
        run: ls -al
